### ISSUE TITLE
SeriesMarker breaks youtube-dl

### ISSUE THREAD

**Issue by tblu** [toroettg/SeriesMarker#3]
Hi once SeriesMarker is installed youtube-dl gives the following error:
youtube-dl https://youtu.be/DjkLlTLMNDs
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws = cls()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 648, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 704, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2049, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2119, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2552, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2892, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2517, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2685, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1490, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1486, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1595, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/SeriesMarker-0.1.0-py3.6.egg-info/PKG-INFO'

I cannot manage them to coexist. As soon as SeriesMarker ist uninstalled, youtube-dl works again.

the url is just an example, it can be reproduced with any url

**Comment by toroettg** [comment]
Thank you for your report! This seems to be a packaging problem. How did you install SeriesMarker? I am assuming you are using Linux. Could you be so kind to tell me what the output for each of the following commands is (having installed SeriesMarker again):

```
umask
ls -la /usr/lib/python3.6/site-packages/ | grep -E "(SeriesMarker|youtube)"
ls -la /usr/lib/python3.6/site-packages/SeriesMarker-0.1.0-py3.6.egg-info/
```
